version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: web-api/Dockerfile

  client:
    image: client
    build:
      context: ../example
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline